services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qualisys1412
      MYSQL_DATABASE: auction_db
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
